
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * Please import the `PrismaClient` class from the `client.ts` file instead.
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "./prismaNamespace"


const config: runtime.GetPrismaClientConfig = {
  "previewFeatures": [
    "views"
  ],
  "clientVersion": "7.10.0",
  "engineVersion": "0edf323efd1d98336f3f0a68684b56f689b900d3",
  "activeProvider": "postgresql",
  "inlineSchema": "// for tests\n\ndatasource db {\n  provider = \"postgresql\"\n  schemas  = [\"pg_catalog\"]\n}\n\ngenerator client {\n  provider        = \"prisma-client\"\n  output          = \"./client\"\n  previewFeatures = [\"views\"]\n}\n\nview pg_timezone_names {\n  name   String  @unique\n  abbrev String\n  is_dst Boolean\n\n  @@schema(\"pg_catalog\")\n}\n",
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"pg_timezone_names\":{\"fields\":[{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"abbrev\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"is_dst\",\"kind\":\"scalar\",\"type\":\"Boolean\"}],\"dbName\":null,\"schema\":\"pg_catalog\"}},\"enums\":{},\"types\":{}}")
config.parameterizationSchema = {
  strings: JSON.parse("[\"where\",\"pg_timezone_names.findUnique\",\"pg_timezone_names.findUniqueOrThrow\",\"orderBy\",\"cursor\",\"pg_timezone_names.findFirst\",\"pg_timezone_names.findFirstOrThrow\",\"pg_timezone_names.findMany\",\"having\",\"_count\",\"_min\",\"_max\",\"pg_timezone_names.groupBy\",\"pg_timezone_names.aggregate\",\"AND\",\"OR\",\"NOT\",\"name\",\"abbrev\",\"is_dst\",\"equals\",\"not\",\"in\",\"notIn\",\"lt\",\"lte\",\"gt\",\"gte\",\"contains\",\"startsWith\",\"endsWith\"]"),
  graph: "GgYHBg4AABUAMA8AAAQAEBAAABUAMBEBAAAAARIBABYAIRMgABcAIQEAAAABACABAAAAAQAgBg4AABUAMA8AAAQAEBAAABUAMBEBABYAIRIBABYAIRMgABcAIQADAAAABAAgAwAABQAwBAAAAQAgAwAAAAQAIAMAAAUAMAQAAAEAIAMAAAAEACADAAAFADAEAAABACADCQAAGAAgCgAAGgAgCwAAGQAgBg4AAA0AMA8AAAoAEBAAAA0AMBEBAA4AIRIBAA4AIRMgAA8AIQMAAAAEACADAAAJADAIAAAKACADAAAABAAgAwAABQAwBAAAAQAgBg4AAA0AMA8AAAoAEBAAAA0AMBEBAA4AIRIBAA4AIRMgAA8AIQ4JAAARACAKAAAUACALAAAUACAUAQAAAAEVAQATACEWAQAAAAQXAQAAAAQYAQAAAAEZAQAAAAEaAQAAAAEbAQAAAAEcAQAAAAEdAQAAAAEeAQAAAAEFCQAAEQAgCgAAEgAgCwAAEgAgFCAAAAABFSAAEAAhBQkAABEAIAoAABIAIAsAABIAIBQgAAAAARUgABAAIQgUAgAAAAEVAgARACEWAgAAAAQXAgAAAAQYAgAAAAEZAgAAAAEaAgAAAAEbAgAAAAECFCAAAAABFSAAEgAhDgkAABEAIAoAABQAIAsAABQAIBQBAAAAARUBABMAIRYBAAAABBcBAAAABBgBAAAAARkBAAAAARoBAAAAARsBAAAAARwBAAAAAR0BAAAAAR4BAAAAAQsUAQAAAAEVAQAUACEWAQAAAAQXAQAAAAQYAQAAAAEZAQAAAAEaAQAAAAEbAQAAAAEcAQAAAAEdAQAAAAEeAQAAAAEGDgAAFQAwDwAABAAQEAAAFQAwEQEAFgAhEgEAFgAhEyAAFwAhCxQBAAAAARUBABQAIRYBAAAABBcBAAAABBgBAAAAARkBAAAAARoBAAAAARsBAAAAARwBAAAAAR0BAAAAAR4BAAAAAQIUIAAAAAEVIAASACEAAAAAAwkAAwoABAsABQAAAAMJAAMKAAQLAAUBAgECAwEFBgEGBwEHCAEMCwINDAY"
}

async function decodeBase64AsWasm(wasmBase64: string): Promise<WebAssembly.Module> {
  const { Buffer } = await import('node:buffer')
  const wasmArray = Buffer.from(wasmBase64, 'base64')
  return new WebAssembly.Module(wasmArray)
}

config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),

  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs")
    return await decodeBase64AsWasm(wasm)
  },

  importName: "./query_compiler_fast_bg.js"
}



export type LogOptions<ClientOptions extends Prisma.PrismaClientOptions> =
  'log' extends keyof ClientOptions ? ClientOptions['log'] extends Array<Prisma.LogLevel | Prisma.LogDefinition> ? Prisma.GetEvents<ClientOptions['log']> : never : never

export interface PrismaClientConstructor {
    /**
   * ## Prisma Client
   * 
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
   * })
   * // Fetch zero or more Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findMany()
   * ```
   * 
   * Read more in our [docs](https://pris.ly/d/client).
   */

  new <
    Options extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options> = LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends { omit: infer U } ? U : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
  >(options: Prisma.PrismaClientConstructorArgs<Options>): PrismaClient<LogOpts, OmitOpts, ExtArgs>
}

/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Pg_timezone_names
 * const pg_timezone_names = await prisma.pg_timezone_names.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */

export interface PrismaClient<
  in LogOpts extends Prisma.LogLevel = never,
  in out OmitOpts extends Prisma.PrismaClientOptions['omit'] = Prisma.PrismaClientOptions['omit'],
  in out ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['other'] }

  $on<V extends LogOpts>(eventType: V, callback: (event: V extends 'query' ? Prisma.QueryEvent : Prisma.LogEvent) => void): PrismaClient;

  /**
   * Connect with the database
   */
  $connect(): runtime.Types.Utils.JsPromise<void>;

  /**
   * Disconnect from the database
   */
  $disconnect(): runtime.Types.Utils.JsPromise<void>;

/**
   * Executes a prepared raw query and returns the number of affected rows.
   * @example
   * ```
   * const result = await prisma.$executeRaw`UPDATE User SET cool = ${true} WHERE email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Executes a raw query and returns the number of affected rows.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$executeRawUnsafe('UPDATE User SET cool = $1 WHERE email = $2 ;', true, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Performs a prepared raw query and returns the `SELECT` data.
   * @example
   * ```
   * const result = await prisma.$queryRaw`SELECT * FROM User WHERE id = ${1} OR email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<T>;

  /**
   * Performs a raw query and returns the `SELECT` data.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$queryRawUnsafe('SELECT * FROM User WHERE id = $1 OR email = $2;', 1, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<T>;


  /**
   * Allows the running of a sequence of read/write operations that are guaranteed to either succeed or fail as a whole.
   * @example
   * ```
   * const [george, bob, alice] = await prisma.$transaction([
   *   prisma.user.create({ data: { name: 'George' } }),
   *   prisma.user.create({ data: { name: 'Bob' } }),
   *   prisma.user.create({ data: { name: 'Alice' } }),
   * ])
   * ```
   * 
   * Read more in our [docs](https://www.prisma.io/docs/orm/prisma-client/queries/transactions).
   */
  $transaction<P extends Prisma.PrismaPromise<any>[]>(arg: [...P], options?: { maxWait?: number, timeout?: number, isolationLevel?: Prisma.TransactionIsolationLevel }): runtime.Types.Utils.JsPromise<runtime.Types.Utils.UnwrapTuple<P>>

  $transaction<R>(fn: (prisma: Omit<PrismaClient, runtime.ITXClientDenyList>) => runtime.Types.Utils.JsPromise<R>, options?: { maxWait?: number, timeout?: number, isolationLevel?: Prisma.TransactionIsolationLevel }): runtime.Types.Utils.JsPromise<R>

  $extends: runtime.Types.Extensions.ExtendsHook<"extends", Prisma.TypeMapCb<OmitOpts>, ExtArgs, runtime.Types.Utils.Call<Prisma.TypeMapCb<OmitOpts>, {
    extArgs: ExtArgs
  }>>

      /**
   * `prisma.pg_timezone_names`: Exposes CRUD operations for the **pg_timezone_names** model.
    * Example usage:
    * ```ts
    * // Fetch zero or more Pg_timezone_names
    * const pg_timezone_names = await prisma.pg_timezone_names.findMany()
    * ```
    */
  get pg_timezone_names(): Prisma.pg_timezone_namesDelegate<ExtArgs, { omit: OmitOpts }>;
}

export function getPrismaClientClass(): PrismaClientConstructor {
  return runtime.getPrismaClient(config) as unknown as PrismaClientConstructor
}
