/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

declare module 'zapatos/custom' {
  export type PgGeography = any;  // replace with your custom type or interface as desired
}
