
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `pg_timezone_names` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model pg_timezone_names
 * 
 */
export type pg_timezone_namesModel = runtime.Types.Result.DefaultSelection<Prisma.$pg_timezone_namesPayload>

export type AggregatePg_timezone_names = {
  _count: Pg_timezone_namesCountAggregateOutputType | null
  _min: Pg_timezone_namesMinAggregateOutputType | null
  _max: Pg_timezone_namesMaxAggregateOutputType | null
}

export type Pg_timezone_namesMinAggregateOutputType = {
  name: string | null
  abbrev: string | null
  is_dst: boolean | null
}

export type Pg_timezone_namesMaxAggregateOutputType = {
  name: string | null
  abbrev: string | null
  is_dst: boolean | null
}

export type Pg_timezone_namesCountAggregateOutputType = {
  name: number
  abbrev: number
  is_dst: number
  _all: number
}


export type Pg_timezone_namesMinAggregateInputType = {
  name?: true
  abbrev?: true
  is_dst?: true
}

export type Pg_timezone_namesMaxAggregateInputType = {
  name?: true
  abbrev?: true
  is_dst?: true
}

export type Pg_timezone_namesCountAggregateInputType = {
  name?: true
  abbrev?: true
  is_dst?: true
  _all?: true
}

export type Pg_timezone_namesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which pg_timezone_names to aggregate.
   */
  where?: Prisma.pg_timezone_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pg_timezone_names to fetch.
   */
  orderBy?: Prisma.pg_timezone_namesOrderByWithRelationInput | Prisma.pg_timezone_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.pg_timezone_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pg_timezone_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pg_timezone_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned pg_timezone_names
  **/
  _count?: true | Pg_timezone_namesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Pg_timezone_namesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Pg_timezone_namesMaxAggregateInputType
}

export type GetPg_timezone_namesAggregateType<T extends Pg_timezone_namesAggregateArgs> = {
      [P in keyof T & keyof AggregatePg_timezone_names]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePg_timezone_names[P]>
    : Prisma.GetScalarType<T[P], AggregatePg_timezone_names[P]>
}




export type pg_timezone_namesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.pg_timezone_namesWhereInput
  orderBy?: Prisma.pg_timezone_namesOrderByWithAggregationInput | Prisma.pg_timezone_namesOrderByWithAggregationInput[]
  by: Prisma.Pg_timezone_namesScalarFieldEnum[] | Prisma.Pg_timezone_namesScalarFieldEnum
  having?: Prisma.pg_timezone_namesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Pg_timezone_namesCountAggregateInputType | true
  _min?: Pg_timezone_namesMinAggregateInputType
  _max?: Pg_timezone_namesMaxAggregateInputType
}

export type Pg_timezone_namesGroupByOutputType = {
  name: string
  abbrev: string
  is_dst: boolean
  _count: Pg_timezone_namesCountAggregateOutputType | null
  _min: Pg_timezone_namesMinAggregateOutputType | null
  _max: Pg_timezone_namesMaxAggregateOutputType | null
}

export type GetPg_timezone_namesGroupByPayload<T extends pg_timezone_namesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Pg_timezone_namesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Pg_timezone_namesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Pg_timezone_namesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Pg_timezone_namesGroupByOutputType[P]>
      }
    >
  >



export type pg_timezone_namesWhereInput = {
  AND?: Prisma.pg_timezone_namesWhereInput | Prisma.pg_timezone_namesWhereInput[]
  OR?: Prisma.pg_timezone_namesWhereInput[]
  NOT?: Prisma.pg_timezone_namesWhereInput | Prisma.pg_timezone_namesWhereInput[]
  name?: Prisma.StringFilter<"pg_timezone_names"> | string
  abbrev?: Prisma.StringFilter<"pg_timezone_names"> | string
  is_dst?: Prisma.BoolFilter<"pg_timezone_names"> | boolean
}

export type pg_timezone_namesOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  abbrev?: Prisma.SortOrder
  is_dst?: Prisma.SortOrder
}

export type pg_timezone_namesWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.pg_timezone_namesWhereInput | Prisma.pg_timezone_namesWhereInput[]
  OR?: Prisma.pg_timezone_namesWhereInput[]
  NOT?: Prisma.pg_timezone_namesWhereInput | Prisma.pg_timezone_namesWhereInput[]
  abbrev?: Prisma.StringFilter<"pg_timezone_names"> | string
  is_dst?: Prisma.BoolFilter<"pg_timezone_names"> | boolean
}, "name">

export type pg_timezone_namesOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  abbrev?: Prisma.SortOrder
  is_dst?: Prisma.SortOrder
  _count?: Prisma.pg_timezone_namesCountOrderByAggregateInput
  _max?: Prisma.pg_timezone_namesMaxOrderByAggregateInput
  _min?: Prisma.pg_timezone_namesMinOrderByAggregateInput
}

export type pg_timezone_namesScalarWhereWithAggregatesInput = {
  AND?: Prisma.pg_timezone_namesScalarWhereWithAggregatesInput | Prisma.pg_timezone_namesScalarWhereWithAggregatesInput[]
  OR?: Prisma.pg_timezone_namesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.pg_timezone_namesScalarWhereWithAggregatesInput | Prisma.pg_timezone_namesScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"pg_timezone_names"> | string
  abbrev?: Prisma.StringWithAggregatesFilter<"pg_timezone_names"> | string
  is_dst?: Prisma.BoolWithAggregatesFilter<"pg_timezone_names"> | boolean
}

export type pg_timezone_namesCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  abbrev?: Prisma.SortOrder
  is_dst?: Prisma.SortOrder
}

export type pg_timezone_namesMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  abbrev?: Prisma.SortOrder
  is_dst?: Prisma.SortOrder
}

export type pg_timezone_namesMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  abbrev?: Prisma.SortOrder
  is_dst?: Prisma.SortOrder
}



export type pg_timezone_namesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  abbrev?: boolean
  is_dst?: boolean
}, ExtArgs["result"]["pg_timezone_names"]>



export type pg_timezone_namesSelectScalar = {
  name?: boolean
  abbrev?: boolean
  is_dst?: boolean
}

export type pg_timezone_namesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "abbrev" | "is_dst", ExtArgs["result"]["pg_timezone_names"]>

export type $pg_timezone_namesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "pg_timezone_names"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    abbrev: string
    is_dst: boolean
  }, ExtArgs["result"]["pg_timezone_names"]>
  composites: {}
}

export type pg_timezone_namesGetPayload<S extends boolean | null | undefined | pg_timezone_namesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload, S>

export type pg_timezone_namesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<pg_timezone_namesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Pg_timezone_namesCountAggregateInputType | true
  }

export interface pg_timezone_namesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['pg_timezone_names'], meta: { name: 'pg_timezone_names' } }
  /**
   * Find zero or one Pg_timezone_names that matches the filter.
   * @param {pg_timezone_namesFindUniqueArgs} args - Arguments to find a Pg_timezone_names
   * @example
   * // Get one Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends pg_timezone_namesFindUniqueArgs>(args: Prisma.SelectSubset<T, pg_timezone_namesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__pg_timezone_namesClient<runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Pg_timezone_names that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {pg_timezone_namesFindUniqueOrThrowArgs} args - Arguments to find a Pg_timezone_names
   * @example
   * // Get one Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends pg_timezone_namesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, pg_timezone_namesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__pg_timezone_namesClient<runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pg_timezone_names that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pg_timezone_namesFindFirstArgs} args - Arguments to find a Pg_timezone_names
   * @example
   * // Get one Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends pg_timezone_namesFindFirstArgs>(args?: Prisma.SelectSubset<T, pg_timezone_namesFindFirstArgs<ExtArgs>>): Prisma.Prisma__pg_timezone_namesClient<runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pg_timezone_names that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pg_timezone_namesFindFirstOrThrowArgs} args - Arguments to find a Pg_timezone_names
   * @example
   * // Get one Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends pg_timezone_namesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, pg_timezone_namesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__pg_timezone_namesClient<runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pg_timezone_names that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pg_timezone_namesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findMany()
   * 
   * // Get first 10 Pg_timezone_names
   * const pg_timezone_names = await prisma.pg_timezone_names.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const pg_timezone_namesWithNameOnly = await prisma.pg_timezone_names.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends pg_timezone_namesFindManyArgs>(args?: Prisma.SelectSubset<T, pg_timezone_namesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$pg_timezone_namesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>


  /**
   * Count the number of Pg_timezone_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pg_timezone_namesCountArgs} args - Arguments to filter Pg_timezone_names to count.
   * @example
   * // Count the number of Pg_timezone_names
   * const count = await prisma.pg_timezone_names.count({
   *   where: {
   *     // ... the filter for the Pg_timezone_names we want to count
   *   }
   * })
  **/
  count<T extends pg_timezone_namesCountArgs>(
    args?: Prisma.Subset<T, pg_timezone_namesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Pg_timezone_namesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Pg_timezone_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Pg_timezone_namesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Pg_timezone_namesAggregateArgs>(args: Prisma.Subset<T, Pg_timezone_namesAggregateArgs>): Prisma.PrismaPromise<GetPg_timezone_namesAggregateType<T>>

  /**
   * Group by Pg_timezone_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {pg_timezone_namesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends pg_timezone_namesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: pg_timezone_namesGroupByArgs['orderBy'] }
      : { orderBy?: pg_timezone_namesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, pg_timezone_namesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPg_timezone_namesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the pg_timezone_names model
 */
readonly fields: pg_timezone_namesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for pg_timezone_names.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__pg_timezone_namesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the pg_timezone_names model
 */
export interface pg_timezone_namesFieldRefs {
  readonly name: Prisma.FieldRef<"pg_timezone_names", 'String'>
  readonly abbrev: Prisma.FieldRef<"pg_timezone_names", 'String'>
  readonly is_dst: Prisma.FieldRef<"pg_timezone_names", 'Boolean'>
}
    

// Custom InputTypes
/**
 * pg_timezone_names findUnique
 */
export type pg_timezone_namesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
  /**
   * Filter, which pg_timezone_names to fetch.
   */
  where: Prisma.pg_timezone_namesWhereUniqueInput
}

/**
 * pg_timezone_names findUniqueOrThrow
 */
export type pg_timezone_namesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
  /**
   * Filter, which pg_timezone_names to fetch.
   */
  where: Prisma.pg_timezone_namesWhereUniqueInput
}

/**
 * pg_timezone_names findFirst
 */
export type pg_timezone_namesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
  /**
   * Filter, which pg_timezone_names to fetch.
   */
  where?: Prisma.pg_timezone_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pg_timezone_names to fetch.
   */
  orderBy?: Prisma.pg_timezone_namesOrderByWithRelationInput | Prisma.pg_timezone_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pg_timezone_names.
   */
  cursor?: Prisma.pg_timezone_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pg_timezone_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pg_timezone_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pg_timezone_names.
   */
  distinct?: Prisma.Pg_timezone_namesScalarFieldEnum | Prisma.Pg_timezone_namesScalarFieldEnum[]
}

/**
 * pg_timezone_names findFirstOrThrow
 */
export type pg_timezone_namesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
  /**
   * Filter, which pg_timezone_names to fetch.
   */
  where?: Prisma.pg_timezone_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pg_timezone_names to fetch.
   */
  orderBy?: Prisma.pg_timezone_namesOrderByWithRelationInput | Prisma.pg_timezone_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for pg_timezone_names.
   */
  cursor?: Prisma.pg_timezone_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pg_timezone_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pg_timezone_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pg_timezone_names.
   */
  distinct?: Prisma.Pg_timezone_namesScalarFieldEnum | Prisma.Pg_timezone_namesScalarFieldEnum[]
}

/**
 * pg_timezone_names findMany
 */
export type pg_timezone_namesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
  /**
   * Filter, which pg_timezone_names to fetch.
   */
  where?: Prisma.pg_timezone_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of pg_timezone_names to fetch.
   */
  orderBy?: Prisma.pg_timezone_namesOrderByWithRelationInput | Prisma.pg_timezone_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing pg_timezone_names.
   */
  cursor?: Prisma.pg_timezone_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` pg_timezone_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` pg_timezone_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of pg_timezone_names.
   */
  distinct?: Prisma.Pg_timezone_namesScalarFieldEnum | Prisma.Pg_timezone_namesScalarFieldEnum[]
}

/**
 * pg_timezone_names without action
 */
export type pg_timezone_namesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the pg_timezone_names
   */
  select?: Prisma.pg_timezone_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the pg_timezone_names
   */
  omit?: Prisma.pg_timezone_namesOmit<ExtArgs> | null
}
