/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';
  import type * as c from 'zapatos/custom';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */

  export type category = 'Cultural' | 'Mixed' | 'Natural';
  export namespace every {
    export type category = ['Cultural', 'Mixed', 'Natural'];
  }
  export type category_short = 'C' | 'C/N' | 'N';
  export namespace every {
    export type category_short = ['C', 'C/N', 'N'];
  }

  /* --- tables --- */

  /**
   * **geography_columns**
   * - View in database
   */
  export namespace geography_columns {
    export type Table = 'geography_columns';
    export interface Selectable {
      /**
      * **geography_columns.f_table_catalog**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_catalog: string | null;
      /**
      * **geography_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema: string | null;
      /**
      * **geography_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name: string | null;
      /**
      * **geography_columns.f_geography_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geography_column: string | null;
      /**
      * **geography_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension: number | null;
      /**
      * **geography_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid: number | null;
      /**
      * **geography_columns.type**
      * - `text` in database
      * - Nullable, no default
      */
      type: string | null;
    }
    export interface JSONSelectable {
      /**
      * **geography_columns.f_table_catalog**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_catalog: string | null;
      /**
      * **geography_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema: string | null;
      /**
      * **geography_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name: string | null;
      /**
      * **geography_columns.f_geography_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geography_column: string | null;
      /**
      * **geography_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension: number | null;
      /**
      * **geography_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid: number | null;
      /**
      * **geography_columns.type**
      * - `text` in database
      * - Nullable, no default
      */
      type: string | null;
    }
    export interface Whereable {
      /**
      * **geography_columns.f_table_catalog**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_catalog?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.f_geography_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geography_column?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geography_columns.type**
      * - `text` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      [key: string]: never;
    }
    export interface Updatable {
      [key: string]: never;
    }
    export type UniqueIndex = never;
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **geometry_columns**
   * - View in database
   */
  export namespace geometry_columns {
    export type Table = 'geometry_columns';
    export interface Selectable {
      /**
      * **geometry_columns.f_table_catalog**
      * - `varchar` in database
      * - Nullable, no default
      */
      f_table_catalog: string | null;
      /**
      * **geometry_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema: string | null;
      /**
      * **geometry_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name: string | null;
      /**
      * **geometry_columns.f_geometry_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geometry_column: string | null;
      /**
      * **geometry_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension: number | null;
      /**
      * **geometry_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid: number | null;
      /**
      * **geometry_columns.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type: string | null;
    }
    export interface JSONSelectable {
      /**
      * **geometry_columns.f_table_catalog**
      * - `varchar` in database
      * - Nullable, no default
      */
      f_table_catalog: string | null;
      /**
      * **geometry_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema: string | null;
      /**
      * **geometry_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name: string | null;
      /**
      * **geometry_columns.f_geometry_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geometry_column: string | null;
      /**
      * **geometry_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension: number | null;
      /**
      * **geometry_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid: number | null;
      /**
      * **geometry_columns.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type: string | null;
    }
    export interface Whereable {
      /**
      * **geometry_columns.f_table_catalog**
      * - `varchar` in database
      * - Nullable, no default
      */
      f_table_catalog?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.f_geometry_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geometry_column?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **geometry_columns.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **geometry_columns.f_table_catalog**
      * - `varchar` in database
      * - Nullable, no default
      */
      f_table_catalog?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.f_geometry_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geometry_column?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **geometry_columns.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **geometry_columns.f_table_catalog**
      * - `varchar` in database
      * - Nullable, no default
      */
      f_table_catalog?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.f_table_schema**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_schema?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.f_table_name**
      * - `name` in database
      * - Nullable, no default
      */
      f_table_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.f_geometry_column**
      * - `name` in database
      * - Nullable, no default
      */
      f_geometry_column?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.coord_dimension**
      * - `int4` in database
      * - Nullable, no default
      */
      coord_dimension?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.srid**
      * - `int4` in database
      * - Nullable, no default
      */
      srid?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **geometry_columns.type**
      * - `varchar` in database
      * - Nullable, no default
      */
      type?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = never;
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **spatial_ref_sys**
   * - Table in database
   */
  export namespace spatial_ref_sys {
    export type Table = 'spatial_ref_sys';
    export interface Selectable {
      /**
      * **spatial_ref_sys.srid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      srid: number;
      /**
      * **spatial_ref_sys.auth_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      auth_name: string | null;
      /**
      * **spatial_ref_sys.auth_srid**
      * - `int4` in database
      * - Nullable, no default
      */
      auth_srid: number | null;
      /**
      * **spatial_ref_sys.srtext**
      * - `varchar` in database
      * - Nullable, no default
      */
      srtext: string | null;
      /**
      * **spatial_ref_sys.proj4text**
      * - `varchar` in database
      * - Nullable, no default
      */
      proj4text: string | null;
    }
    export interface JSONSelectable {
      /**
      * **spatial_ref_sys.srid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      srid: number;
      /**
      * **spatial_ref_sys.auth_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      auth_name: string | null;
      /**
      * **spatial_ref_sys.auth_srid**
      * - `int4` in database
      * - Nullable, no default
      */
      auth_srid: number | null;
      /**
      * **spatial_ref_sys.srtext**
      * - `varchar` in database
      * - Nullable, no default
      */
      srtext: string | null;
      /**
      * **spatial_ref_sys.proj4text**
      * - `varchar` in database
      * - Nullable, no default
      */
      proj4text: string | null;
    }
    export interface Whereable {
      /**
      * **spatial_ref_sys.srid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      srid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **spatial_ref_sys.auth_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      auth_name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **spatial_ref_sys.auth_srid**
      * - `int4` in database
      * - Nullable, no default
      */
      auth_srid?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **spatial_ref_sys.srtext**
      * - `varchar` in database
      * - Nullable, no default
      */
      srtext?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **spatial_ref_sys.proj4text**
      * - `varchar` in database
      * - Nullable, no default
      */
      proj4text?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **spatial_ref_sys.srid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      srid: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **spatial_ref_sys.auth_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      auth_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **spatial_ref_sys.auth_srid**
      * - `int4` in database
      * - Nullable, no default
      */
      auth_srid?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **spatial_ref_sys.srtext**
      * - `varchar` in database
      * - Nullable, no default
      */
      srtext?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **spatial_ref_sys.proj4text**
      * - `varchar` in database
      * - Nullable, no default
      */
      proj4text?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **spatial_ref_sys.srid**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      srid?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **spatial_ref_sys.auth_name**
      * - `varchar` in database
      * - Nullable, no default
      */
      auth_name?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **spatial_ref_sys.auth_srid**
      * - `int4` in database
      * - Nullable, no default
      */
      auth_srid?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **spatial_ref_sys.srtext**
      * - `varchar` in database
      * - Nullable, no default
      */
      srtext?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **spatial_ref_sys.proj4text**
      * - `varchar` in database
      * - Nullable, no default
      */
      proj4text?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'spatial_ref_sys_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **strings**
   * - Table in database
   */
  export namespace strings {
    export type Table = 'strings';
    export interface Selectable {
      /**
      * **strings.id**
      * - `int4` in database
      * - Generated column
      */
      id: number;
      /**
      * **strings.string**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      string: string;
    }
    export interface JSONSelectable {
      /**
      * **strings.id**
      * - `int4` in database
      * - Generated column
      */
      id: number;
      /**
      * **strings.string**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      string: string;
    }
    export interface Whereable {
      /**
      * **strings.id**
      * - `int4` in database
      * - Generated column
      */
      id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **strings.string**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      string?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **strings.string**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      string: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **strings.string**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      string?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'strings_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **whc_sites_2021**
   * - Table in database
   */
  export namespace whc_sites_2021 {
    export type Table = 'whc_sites_2021';
    export interface Selectable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis: string | null;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en: string | null;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr: string | null;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates: string | null;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger: number | null;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end: number | null;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list: string | null;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares: number | null;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code: string | null;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code: string | null;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location: c.PgGeography | null;
    }
    export interface JSONSelectable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis: string | null;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en: string | null;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr: string | null;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates: string | null;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger: number | null;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end: number | null;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list: string | null;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares: number | null;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code: string | null;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code: string | null;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location: c.PgGeography | null;
    }
    export interface Whereable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category?: category | db.Parameter<category> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, category | db.Parameter<category> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short?: category_short | db.Parameter<category_short> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, category_short | db.Parameter<category_short> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, c.PgGeography | db.Parameter<c.PgGeography> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category: category | db.Parameter<category> | db.SQLFragment;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short: category_short | db.Parameter<category_short> | db.SQLFragment;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **whc_sites_2021.unique_number**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      unique_number?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.id_no**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      id_no?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.rev_bis**
      * - `text` in database
      * - Nullable, no default
      */
      rev_bis?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.short_description_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.short_description_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      short_description_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.justification_en**
      * - `text` in database
      * - Nullable, no default
      */
      justification_en?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.justification_fr**
      * - `text` in database
      * - Nullable, no default
      */
      justification_fr?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.date_inscribed**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      date_inscribed?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.secondary_dates**
      * - `text` in database
      * - Nullable, no default
      */
      secondary_dates?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.danger**
      * - `int4` in database
      * - Nullable, no default
      */
      danger?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.date_end**
      * - `int4` in database
      * - Nullable, no default
      */
      date_end?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.danger_list**
      * - `text` in database
      * - Nullable, no default
      */
      danger_list?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.longitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      longitude?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.latitude**
      * - `float8` in database
      * - `NOT NULL`, no default
      */
      latitude?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.area_hectares**
      * - `float8` in database
      * - Nullable, no default
      */
      area_hectares?: number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.c1**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c1?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c2**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c2?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c3**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c3?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c4**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c4?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c5**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c5?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.c6**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      c6?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n7**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n7?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n8**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n8?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n9**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n9?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.n10**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      n10?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.criteria_txt**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      criteria_txt?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.category**
      * - `category` in database
      * - `NOT NULL`, no default
      */
      category?: category | db.Parameter<category> | db.SQLFragment | db.SQLFragment<any, category | db.Parameter<category> | db.SQLFragment>;
      /**
      * **whc_sites_2021.category_short**
      * - `category_short` in database
      * - `NOT NULL`, no default
      */
      category_short?: category_short | db.Parameter<category_short> | db.SQLFragment | db.SQLFragment<any, category_short | db.Parameter<category_short> | db.SQLFragment>;
      /**
      * **whc_sites_2021.states_name_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.states_name_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      states_name_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.region_en**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_en?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.region_fr**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      region_fr?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **whc_sites_2021.iso_code**
      * - `text` in database
      * - Nullable, no default
      */
      iso_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.udnp_code**
      * - `text` in database
      * - Nullable, no default
      */
      udnp_code?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **whc_sites_2021.transboundary**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
      transboundary?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **whc_sites_2021.location**
      * - `geography` in database
      * - Nullable, no default
      */
      location?: c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, c.PgGeography | db.Parameter<c.PgGeography> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'whc_sites_2021_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = geography_columns.Table | geometry_columns.Table | spatial_ref_sys.Table | strings.Table | whc_sites_2021.Table;
    export type Selectable = geography_columns.Selectable | geometry_columns.Selectable | spatial_ref_sys.Selectable | strings.Selectable | whc_sites_2021.Selectable;
    export type JSONSelectable = geography_columns.JSONSelectable | geometry_columns.JSONSelectable | spatial_ref_sys.JSONSelectable | strings.JSONSelectable | whc_sites_2021.JSONSelectable;
    export type Whereable = geography_columns.Whereable | geometry_columns.Whereable | spatial_ref_sys.Whereable | strings.Whereable | whc_sites_2021.Whereable;
    export type Insertable = geography_columns.Insertable | geometry_columns.Insertable | spatial_ref_sys.Insertable | strings.Insertable | whc_sites_2021.Insertable;
    export type Updatable = geography_columns.Updatable | geometry_columns.Updatable | spatial_ref_sys.Updatable | strings.Updatable | whc_sites_2021.Updatable;
    export type UniqueIndex = geography_columns.UniqueIndex | geometry_columns.UniqueIndex | spatial_ref_sys.UniqueIndex | strings.UniqueIndex | whc_sites_2021.UniqueIndex;
    export type Column = geography_columns.Column | geometry_columns.Column | spatial_ref_sys.Column | strings.Column | whc_sites_2021.Column;
  
    export type AllBaseTables = [spatial_ref_sys.Table, strings.Table, whc_sites_2021.Table];
    export type AllForeignTables = [];
    export type AllViews = [geography_columns.Table, geometry_columns.Table];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [geography_columns.Table, geometry_columns.Table, spatial_ref_sys.Table, strings.Table, whc_sites_2021.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "geography_columns": geography_columns.Selectable;
    "geometry_columns": geometry_columns.Selectable;
    "spatial_ref_sys": spatial_ref_sys.Selectable;
    "strings": strings.Selectable;
    "whc_sites_2021": whc_sites_2021.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "geography_columns": geography_columns.JSONSelectable;
    "geometry_columns": geometry_columns.JSONSelectable;
    "spatial_ref_sys": spatial_ref_sys.JSONSelectable;
    "strings": strings.JSONSelectable;
    "whc_sites_2021": whc_sites_2021.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "geography_columns": geography_columns.Whereable;
    "geometry_columns": geometry_columns.Whereable;
    "spatial_ref_sys": spatial_ref_sys.Whereable;
    "strings": strings.Whereable;
    "whc_sites_2021": whc_sites_2021.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "geography_columns": geography_columns.Insertable;
    "geometry_columns": geometry_columns.Insertable;
    "spatial_ref_sys": spatial_ref_sys.Insertable;
    "strings": strings.Insertable;
    "whc_sites_2021": whc_sites_2021.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "geography_columns": geography_columns.Updatable;
    "geometry_columns": geometry_columns.Updatable;
    "spatial_ref_sys": spatial_ref_sys.Updatable;
    "strings": strings.Updatable;
    "whc_sites_2021": whc_sites_2021.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "geography_columns": geography_columns.UniqueIndex;
    "geometry_columns": geometry_columns.UniqueIndex;
    "spatial_ref_sys": spatial_ref_sys.UniqueIndex;
    "strings": strings.UniqueIndex;
    "whc_sites_2021": whc_sites_2021.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "geography_columns": geography_columns.Column;
    "geometry_columns": geometry_columns.Column;
    "spatial_ref_sys": spatial_ref_sys.Column;
    "strings": strings.Column;
    "whc_sites_2021": whc_sites_2021.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "geography_columns": geography_columns.SQL;
    "geometry_columns": geometry_columns.SQL;
    "spatial_ref_sys": spatial_ref_sys.SQL;
    "strings": strings.SQL;
    "whc_sites_2021": whc_sites_2021.SQL;
  }[T];

}
